try{const p=localStorage.getItem('pharo-ca-theme')||'auto',dark=matchMedia('(prefers-color-scheme: dark)').matches;document.documentElement.dataset.theme=p==='auto'?(dark?'dark':'light'):p}catch(_e){}

document.addEventListener('DOMContentLoaded', () => {
(() => {
  const $=id=>document.getElementById(id), state={ws:null,pending:new Map(),seq:0,agentId:null,agentDescriptor:null,modelId:null,modelDescriptor:null,modelSupportsImages:false,modelSupportsReasoning:false,sessionId:null,viewEntryId:null,runId:null,inspectRunId:null,terminalRunId:null,lastEventSequence:0,subscriptionId:null,streamKind:null,streamNode:null,toolGroup:null,reviewRunId:null,reviewNextChangeId:null,reviewHasMore:false,reviewItemsById:new Map(),treeRefreshPending:false,treeRefreshInFlight:false,plannedCheckpointId:null,lastContext:null,lastUsage:null,lastTelemetry:null,themePreference:'auto',commandCompletionItems:[],commandCompletionIndex:0,commandCompletionGeneration:0,sessionItems:[],sessionFilter:'',pendingSteeringNodes:[]};
  const status=(text,ok=false)=>{$('status').textContent=text;$('status').className='status'+(ok?' ok':'')};
  const request=(method,params={})=>new Promise((resolve,reject)=>{if(!state.ws||state.ws.readyState!==1)return reject(new Error('WebSocket not connected'));const id='web-'+(++state.seq);state.pending.set(id,{resolve,reject,method});state.ws.send(JSON.stringify({protocolVersion:1,type:'request',id,method,params}));});
  const call=async(method,params={})=>{const r=await request(method,params);if(!r.ok)throw Object.assign(new Error(r.error?.message||'Request failed'),{response:r});return r.result};
  const paramsAgent=extra=>Object.assign(state.agentId?{agentId:state.agentId}:{},extra||{});
  const themeMedia=matchMedia('(prefers-color-scheme: dark)');
  function readThemePreference(){try{return localStorage.getItem('pharo-ca-theme')||'auto'}catch(_e){return'auto'}}
  function applyThemePreference(value,persist=false){const pref=['auto','light','dark'].includes(value)?value:'auto';state.themePreference=pref;const resolved=pref==='auto'?(themeMedia.matches?'dark':'light'):pref;document.documentElement.dataset.theme=resolved;$('theme').value=pref;if(persist)try{localStorage.setItem('pharo-ca-theme',pref)}catch(_e){}}
  function inspectButton(kind,params,title='Inspect in Pharo'){const b=document.createElement('button');b.type='button';b.className='inspect-link';b.textContent='i';b.title=title;b.onclick=e=>{e.preventDefault();e.stopPropagation();inspectEntity(kind,params).catch(showError)};return b}
  async function inspectEntity(kind,params={}){return call('inspect.open',Object.assign({kind},params))}
  const formatTokens=n=>Number.isFinite(Number(n))?Number(n)>=1000000?(Number(n)/1000000).toFixed(Number(n)>=10000000?0:1)+'m':Number(n)>=1000?(Number(n)/1000).toFixed(Number(n)>=10000?0:1)+'k':String(Number(n)):'—';
  function renderTelemetry(){const telemetry=state.lastTelemetry||{},calls=telemetry.modelCalls||[],latest=calls.length?calls[calls.length-1]:null,context=state.lastContext||latest?.context||null,usage=state.lastUsage||latest?.usage||null,contextSize=Number(context?.contextSize||state.modelDescriptor?.contextSize||0),contextPrompt=Number(usage?.promptTokens||latest?.usage?.promptTokens||0),totalPrompt=Number(telemetry.promptTokens||contextPrompt||0),estimated=Number(context?.estimatedInputTokens||0),used=contextPrompt>0?contextPrompt:estimated,prefix=contextPrompt>0?'':'~',pct=contextSize>0&&used>0?Math.min(999,Math.round(used*100/contextSize)):null,out=Number(telemetry.completionTokens||usage?.completionTokens||0),reason=Number(telemetry.reasoningTokens||usage?.reasoningTokens||0),rate=Number(telemetry.tokensPerSecond||latest?.tokensPerSecond),ttft=Number(latest?.timeToFirstOutputMilliseconds);const parts=['ctx '+(used>0?prefix+formatTokens(used):'—')+'/'+(contextSize>0?formatTokens(contextSize):'?')+(pct!==null?' ('+pct+'%)':''),'in '+(totalPrompt>0?formatTokens(totalPrompt):(estimated>0?'~'+formatTokens(estimated):'—')),'out '+(out>0?formatTokens(out):'—')];if(reason>0)parts.push('reason '+formatTokens(reason));parts.push(Number.isFinite(rate)&&rate>0?rate.toFixed(rate>=100?0:rate>=10?1:2)+' tok/s':'— tok/s');if(Number.isFinite(ttft)&&ttft>=0)parts.push('TTFT '+(ttft<1000?Math.round(ttft)+' ms':(ttft/1000).toFixed(2)+' s'));$('telemetryInfo').textContent=parts.join(' · ');const details=[];if(state.modelDescriptor?.name)details.push('model: '+state.modelDescriptor.name);if(context){details.push(contextPrompt>0?'context usage: provider reported':'context usage: estimated before request');details.push('reserved output: '+formatTokens(context.reservedOutputTokens));details.push('safety margin: '+formatTokens(context.safetyMarginTokens));if(context.compacted)details.push('context compacted');if(context.omittedMessageCount)details.push('omitted messages: '+context.omittedMessageCount)}if(telemetry.modelRequestCount)details.push('model calls: '+telemetry.modelRequestCount);$('telemetryInfo').title=details.join('\n')||'Run telemetry'}
  function resetRunTelemetry(runId=null){state.inspectRunId=runId;state.lastContext=null;state.lastUsage=null;state.lastTelemetry=null;$('inspectRun').disabled=!runId;renderTelemetry()}
  async function refreshRunTelemetry(runId){if(!runId)return;try{const snap=await call('runs.get',{runId});if(state.inspectRunId&&state.inspectRunId!==runId)return;state.inspectRunId=runId;state.lastTelemetry=snap.telemetry||null;const calls=state.lastTelemetry?.modelCalls||[];if(calls.length){const latest=calls[calls.length-1];state.lastContext=latest.context||state.lastContext;state.lastUsage=latest.usage||state.lastUsage}$('inspectRun').disabled=false;renderTelemetry()}catch(e){if(e.response?.error?.code!=='run_not_found')throw e}}
  const messageText=m=>{if(!m)return'';if(typeof m==='string')return m;if(typeof m.content==='string')return m.content;if(Array.isArray(m.contentParts)){const normal=m.contentParts.filter(p=>!p.metadata?.attachment).map(p=>p.value??p.text??p.content??'').join('');const names=[...new Set(m.contentParts.filter(p=>p.metadata?.attachment&&p.metadata?.kind!=='imageLabel').map(p=>p.metadata?.name).filter(Boolean))];return normal+(names.length?'\n'+names.map(n=>'[attached: '+n+']').join('\n'):'')}if(Array.isArray(m.content))return m.content.map(p=>typeof p==='string'?p:(p.text||'')).join('');return m.text||m.payload?.text||''};
  function transcriptNearBottom(){const t=$('transcript');return t.scrollHeight-t.scrollTop-t.clientHeight<80;}
  function scrollTranscriptToBottom(){const t=$('transcript');t.scrollTop=t.scrollHeight;}
  function safeLinkTarget(raw){const value=String(raw||'').trim();if(value.startsWith('#'))return value;try{const url=new URL(value,location.href);if(['http:','https:','mailto:'].includes(url.protocol))return value}catch(_e){}return null;}
  function appendInline(parent,text){let rest=String(text||'');const rules=[
    {kind:'code',re:/`([^`\n]+)`/},
    {kind:'link',re:/\[([^\]\n]+)\]\(([^)\s]+)(?:\s+"[^"]*")?\)/},
    {kind:'strong',re:/\*\*([^*\n]+)\*\*|__([^_\n]+)__/},
    {kind:'strike',re:/~~([^~\n]+)~~/},
    {kind:'em',re:/\*([^*\n]+)\*|_([^_\n]+)_/}
  ];
  while(rest){let winner=null;for(const rule of rules){const match=rule.re.exec(rest);if(match&&(!winner||match.index<winner.match.index))winner={rule,match};}if(!winner){parent.appendChild(document.createTextNode(rest));break;}if(winner.match.index>0)parent.appendChild(document.createTextNode(rest.slice(0,winner.match.index)));const raw=winner.match[0],kind=winner.rule.kind,m=winner.match;if(kind==='code'){const code=document.createElement('code');code.textContent=m[1];parent.appendChild(code);}else if(kind==='link'){const href=safeLinkTarget(m[2]);if(href){const a=document.createElement('a');a.href=href;a.target='_blank';a.rel='noopener noreferrer';appendInline(a,m[1]);parent.appendChild(a);}else parent.appendChild(document.createTextNode(raw));}else{const tag=kind==='strong'?'strong':kind==='strike'?'del':'em',el=document.createElement(tag);appendInline(el,m[1]||m[2]||'');parent.appendChild(el);}rest=rest.slice(winner.match.index+raw.length);}}
  function copyText(text,button){const done=()=>{if(!button)return;const before=button.textContent;button.textContent='Copied';setTimeout(()=>{button.textContent=before},1200)};if(navigator.clipboard?.writeText){navigator.clipboard.writeText(String(text||'')).then(done).catch(()=>fallbackCopy(text,button));}else fallbackCopy(text,button);}
  function fallbackCopy(text,button){const area=document.createElement('textarea');area.value=String(text||'');area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{document.execCommand('copy');if(button){const before=button.textContent;button.textContent='Copied';setTimeout(()=>{button.textContent=before},1200)}}finally{area.remove();}}
  function prismLanguageName(language){const raw=String(language||'').trim().toLowerCase(),aliases={st:'smalltalk',pharo:'smalltalk',smalltalk:'smalltalk',js:'javascript',javascript:'javascript',ts:'typescript',typescript:'typescript',cs:'csharp','c#':'csharp',csharp:'csharp',py:'python',python:'python',sh:'bash',shell:'bash',bash:'bash',md:'markdown',markdown:'markdown',patch:'diff',diff:'diff',json:'json',sql:'sql',c:'c',cpp:'cpp','c++':'cpp',java:'java'};return aliases[raw]||raw.replace(/[^a-z0-9_-]/g,'-');}
  function codeBlock(text,language){const wrap=document.createElement('div');wrap.className='code-block';const bar=document.createElement('div');bar.className='code-toolbar';const label=document.createElement('span');label.className='code-language';label.textContent=language||'code';const copy=document.createElement('button');copy.type='button';copy.className='code-copy';copy.textContent='Copy';copy.onclick=()=>copyText(text,copy);bar.append(label,copy);const pre=document.createElement('pre'),code=document.createElement('code'),highlightLanguage=prismLanguageName(language);if(highlightLanguage)code.className='language-'+highlightLanguage;code.textContent=text;if(highlightLanguage&&window.Prism?.languages?.[highlightLanguage])window.Prism.highlightElement(code);pre.appendChild(code);wrap.append(bar,pre);return wrap;}
  function tableCells(line){let value=String(line).trim();if(value.startsWith('|'))value=value.slice(1);if(value.endsWith('|'))value=value.slice(0,-1);return value.split('|').map(cell=>cell.trim());}
  function isTableDivider(line){const cells=tableCells(line);return cells.length>0&&cells.every(cell=>/^:?-{3,}:?$/.test(cell));}
  function startsBlock(lines,index){const line=lines[index]??'';if(!line.trim())return true;if(/^\s*```/.test(line)||/^\s{0,3}#{1,6}\s+/.test(line)||/^\s{0,3}>\s?/.test(line)||/^\s{0,3}[-+*]\s+/.test(line)||/^\s{0,3}\d+[.)]\s+/.test(line)||/^\s{0,3}((\*\s*){3,}|(-\s*){3,}|(_\s*){3,})$/.test(line))return true;return index+1<lines.length&&line.includes('|')&&isTableDivider(lines[index+1]);}
  function markdownToFragment(markdown){const fragment=document.createDocumentFragment(),lines=String(markdown||'').replace(/\r\n?/g,'\n').split('\n');let i=0;while(i<lines.length){const line=lines[i];if(!line.trim()){i++;continue;}
    const fence=/^\s*```\s*([^`]*)$/.exec(line);if(fence){const language=fence[1].trim(),body=[];i++;while(i<lines.length&&!/^\s*```\s*$/.test(lines[i]))body.push(lines[i++]);if(i<lines.length)i++;fragment.appendChild(codeBlock(body.join('\n'),language));continue;}
    if(i+1<lines.length&&line.includes('|')&&isTableDivider(lines[i+1])){const headers=tableCells(line),table=document.createElement('table'),thead=document.createElement('thead'),tr=document.createElement('tr');headers.forEach(text=>{const th=document.createElement('th');appendInline(th,text);tr.appendChild(th)});thead.appendChild(tr);table.appendChild(thead);i+=2;const tbody=document.createElement('tbody');while(i<lines.length&&lines[i].trim()&&lines[i].includes('|')&&!startsBlock(lines,i)){const row=document.createElement('tr');tableCells(lines[i]).forEach(text=>{const td=document.createElement('td');appendInline(td,text);row.appendChild(td)});tbody.appendChild(row);i++;}if(tbody.children.length)table.appendChild(tbody);fragment.appendChild(table);continue;}
    const heading=/^\s{0,3}(#{1,6})\s+(.+?)\s*#*\s*$/.exec(line);if(heading){const h=document.createElement('h'+heading[1].length);appendInline(h,heading[2]);fragment.appendChild(h);i++;continue;}
    if(/^\s{0,3}((\*\s*){3,}|(-\s*){3,}|(_\s*){3,})$/.test(line)){fragment.appendChild(document.createElement('hr'));i++;continue;}
    if(/^\s{0,3}>\s?/.test(line)){const quoteLines=[];while(i<lines.length&&/^\s{0,3}>\s?/.test(lines[i]))quoteLines.push(lines[i++].replace(/^\s{0,3}>\s?/,''));const quote=document.createElement('blockquote');quote.appendChild(markdownToFragment(quoteLines.join('\n')));fragment.appendChild(quote);continue;}
    const unordered=/^\s{0,3}[-+*]\s+(.+)$/.exec(line);if(unordered){const list=document.createElement('ul');while(i<lines.length){const m=/^\s{0,3}[-+*]\s+(.+)$/.exec(lines[i]);if(!m)break;const li=document.createElement('li');appendInline(li,m[1]);list.appendChild(li);i++;}fragment.appendChild(list);continue;}
    const ordered=/^\s{0,3}\d+[.)]\s+(.+)$/.exec(line);if(ordered){const list=document.createElement('ol');while(i<lines.length){const m=/^\s{0,3}\d+[.)]\s+(.+)$/.exec(lines[i]);if(!m)break;const li=document.createElement('li');appendInline(li,m[1]);list.appendChild(li);i++;}fragment.appendChild(list);continue;}
    const paragraph=[];while(i<lines.length&&lines[i].trim()&&!startsBlock(lines,i)){paragraph.push(lines[i++]);}if(!paragraph.length){paragraph.push(lines[i++]);}const p=document.createElement('p');appendInline(p,paragraph.join(' '));fragment.appendChild(p);
  }return fragment;}
  function renderMarkdownInto(element,text){element.textContent='';element.classList.remove('plain');element.classList.add('markdown-body');element.appendChild(markdownToFragment(text));}
  window.PharoCAMarkdown={renderInto:renderMarkdownInto,toFragment:markdownToFragment,safeLinkTarget};
  function appendTranscriptElement(node){const stick=transcriptNearBottom();$('transcript').appendChild(node);if(stick)scrollTranscriptToBottom();return node;}
  function addMessage(role,text,cls=role,options={}){const raw=String(text||''),n=document.createElement('div');n.className='message '+(cls||'');n._rawText=raw;const header=document.createElement('div');header.className='message-header';const r=document.createElement('div');r.className='role';r.textContent=role;header.appendChild(r);if(role==='assistant'){const actions=document.createElement('div');actions.className='message-actions';const copy=document.createElement('button');copy.type='button';copy.className='message-action';copy.textContent='Copy';copy.onclick=()=>copyText(n._rawText,copy);actions.appendChild(copy);header.appendChild(actions);}const body=document.createElement('div');body.className='message-body';n._body=body;n.append(header,body);const markdown=options.markdown!==undefined?options.markdown:role==='assistant';if(markdown)renderMarkdownInto(body,raw);else{body.classList.add('plain');body.textContent=raw;}return appendTranscriptElement(n);}
  function appendNode(node,text){if(!node)return;const stick=transcriptNearBottom(),chunk=String(text||'');node._rawText=(node._rawText||'')+chunk;const body=node._body||node;body.appendChild(document.createTextNode(chunk));if(stick)scrollTranscriptToBottom();}
  function finalizeAssistantMarkdown(node){if(!node)return;const stick=transcriptNearBottom();renderMarkdownInto(node._body||node,node._rawText||'');if(stick)scrollTranscriptToBottom();}
  function compactPreview(value,max=120){const text=String(value??'').replace(/\s+/g,' ').trim();if(text.length<=max)return text;return '…'+text.slice(-(max-1));}
  function prettyValue(value){if(value===undefined)return'';if(typeof value==='string'){const trimmed=value.trim();if((trimmed.startsWith('{')&&trimmed.endsWith('}'))||(trimmed.startsWith('[')&&trimmed.endsWith(']'))){try{return JSON.stringify(JSON.parse(trimmed),null,2)}catch(_e){}}return value;}try{return JSON.stringify(value,null,2)}catch(_e){return String(value)}}
  function createReasoningTrace(text='',active=false){const node=document.createElement('details');node.className='trace reasoning-trace';node.title='Expand/collapse reasoning';const summary=document.createElement('summary'),kind=document.createElement('span'),preview=document.createElement('span'),meta=document.createElement('span'),body=document.createElement('div');kind.className='trace-kind';preview.className='trace-preview';meta.className='trace-meta';body.className='trace-body';summary.append(kind,preview,meta);node.append(summary,body);node._kind=kind;node._preview=preview;node._meta=meta;node._body=body;node._rawText='';appendTranscriptElement(node);updateReasoningTrace(node,text,active,false);return node;}
  function updateReasoningTrace(node,text='',active=true,append=true){if(!node)return;const stick=transcriptNearBottom(),chunk=String(text||'');if(append){node._rawText=(node._rawText||'')+chunk;if(chunk)node._body.appendChild(document.createTextNode(chunk));}else{node._rawText=chunk;node._body.textContent=chunk;}node._kind.textContent=active?'Thinking':'Thought';node._preview.textContent=compactPreview(node._rawText)||(active?'working…':'');node._meta.textContent=active?'live':'';if(stick)scrollTranscriptToBottom();}
  function toolStatusPresentation(status){const map={requested:['→','requested'],modified:['~','modified'],queued:['○','queued'],running:['…','running'],completed:['✓','done'],skipped:['↷','skipped'],rejected:['!','rejected']};return map[status]||['·',status||'pending'];}
  function toolProgressPreview(progress){if(progress&&typeof progress==='object'){const parts=[];if(progress.message)parts.push(String(progress.message));if(progress.current!==undefined&&progress.total!==undefined)parts.push(String(progress.current)+'/'+String(progress.total));else if(progress.current!==undefined)parts.push(String(progress.current));return compactPreview(parts.join(' '),72);}return compactPreview(prettyValue(progress),72);}
  function createToolGroup(active=false){const group=document.createElement('details');group.className='trace tool-group';group.title='Expand/collapse tool calls';const summary=document.createElement('summary'),kind=document.createElement('span'),preview=document.createElement('span'),meta=document.createElement('span'),list=document.createElement('div');kind.className='trace-kind';kind.textContent='Tools';preview.className='trace-preview';meta.className='trace-meta';list.className='tool-list';summary.append(kind,preview,meta);group.append(summary,list);group._preview=preview;group._meta=meta;group._list=list;group._tools=new Map();group._active=active;appendTranscriptElement(group);updateToolGroupSummary(group);return group;}
  function toolIdentifier(payload){const value=payload?.id??payload?.toolCallId;return value===undefined||value===null||String(value)===''?'tool-'+Math.random().toString(36).slice(2):String(value);}
  function ensureToolRow(group,payload={}){const id=toolIdentifier(payload);let row=group._tools.get(id);if(row)return row;const node=document.createElement('details'),summary=document.createElement('summary'),status=document.createElement('span'),name=document.createElement('span'),preview=document.createElement('span'),stateLabel=document.createElement('span'),detail=document.createElement('pre');node.className='tool-row';node.title='Expand/collapse tool arguments and result';status.className='tool-status';name.className='tool-name';preview.className='tool-preview';stateLabel.className='tool-state';detail.className='tool-detail';summary.append(status,name,preview,stateLabel);node.append(summary,detail);row={id,node,status,name,preview,stateLabel,detail,state:{id,status:'requested',name:payload.name||'tool',index:payload.index,argumentsJSON:payload.argumentsJSON}};group._tools.set(id,row);group._list.appendChild(node);return row;}
  function toolDetailText(state){const sections=['id: '+state.id];if(state.index!==undefined&&state.index!==null)sections.push('index: '+state.index);if(state.originalName)sections.push('original name: '+state.originalName);if(state.argumentsJSON!==undefined&&state.argumentsJSON!==null&&String(state.argumentsJSON)!=='')sections.push('arguments:\n'+prettyValue(state.argumentsJSON));if(state.progress!==undefined)sections.push('progress:\n'+prettyValue(state.progress));if(state.result!==undefined)sections.push('result:\n'+prettyValue(state.result));return sections.join('\n\n');}
  function updateToolRow(group,type,payload={}){const row=ensureToolRow(group,payload),s=row.state;group._latestToolId=row.id;s.id=row.id;if(payload.name)s.name=payload.name;if(payload.originalName)s.originalName=payload.originalName;if(payload.index!==undefined)s.index=payload.index;if(payload.argumentsJSON!==undefined)s.argumentsJSON=payload.argumentsJSON;if(payload.progress!==undefined)s.progress=payload.progress;if(payload.result!==undefined)s.result=payload.result;if(type==='toolRequested')s.status='requested';else if(type==='toolInvocationModified')s.status='modified';else if(type==='toolInvocationRejected'||type==='toolExecutionRejected')s.status='rejected';else if(type==='toolExecutionQueued')s.status='queued';else if(type==='toolExecutionStarted'||type==='toolExecutionProgress')s.status='running';else if(type==='toolExecutionCompleted'||type==='historicalToolResult'||type==='toolResultIntercepted')s.status='completed';else if(type==='toolExecutionSkipped')s.status=s.status==='rejected'?'rejected':'skipped';const presentation=toolStatusPresentation(s.status);row.node.dataset.status=s.status;row.status.textContent=presentation[0];row.name.textContent=s.name||'tool';row.stateLabel.textContent=presentation[1];const hint=s.status==='running'&&s.progress!==undefined?toolProgressPreview(s.progress):s.argumentsJSON!==undefined?compactPreview(s.argumentsJSON,90):s.result!==undefined?compactPreview(prettyValue(s.result),90):'';row.preview.textContent=hint;row.detail.textContent=toolDetailText(s);updateToolGroupSummary(group);return row;}
  function updateToolGroupSummary(group){const rows=[...group._tools.values()],states=rows.map(r=>r.state),n=states.length,running=states.filter(s=>['requested','modified','queued','running'].includes(s.status)).length,done=states.filter(s=>s.status==='completed').length,rejected=states.filter(s=>s.status==='rejected').length,skipped=states.filter(s=>s.status==='skipped').length,latest=(group._latestToolId&&group._tools.get(group._latestToolId)?.state)||(states.length?states[states.length-1]:null),parts=[n+' tool'+(n===1?'':'s')];if(running)parts.push(running+' active');if(done)parts.push(done+' done');if(rejected)parts.push(rejected+' rejected');if(skipped)parts.push(skipped+' skipped');if(latest?.name){let latestText='latest: '+latest.name+' '+toolStatusPresentation(latest.status)[1];if(latest.status==='running'&&latest.progress!==undefined){const progress=toolProgressPreview(latest.progress);if(progress)latestText+=' — '+progress;}parts.push(latestText);}group._preview.textContent=parts.join(' · ');group._meta.textContent=group._active?'live':'';}
  function finishToolGroup(group){if(!group)return;group._active=false;updateToolGroupSummary(group);}
  function resetLiveStreamState(){state.streamKind=null;state.streamNode=null;state.toolGroup=null;}
  function finishLiveStreamSegment(){if(state.streamKind==='assistant')finalizeAssistantMarkdown(state.streamNode);else if(state.streamKind==='reasoning')updateReasoningTrace(state.streamNode,'',false,true);else if(state.streamKind==='tools')finishToolGroup(state.toolGroup);resetLiveStreamState();}
  function beginAssistantSegment(){if(state.streamKind==='assistant'&&state.streamNode)return state.streamNode;finishLiveStreamSegment();state.streamKind='assistant';state.streamNode=addMessage('assistant','','assistant stream-segment',{markdown:false});return state.streamNode;}
  function beginReasoningSegment(){if(state.streamKind==='reasoning'&&state.streamNode)return state.streamNode;finishLiveStreamSegment();state.streamKind='reasoning';state.streamNode=createReasoningTrace('',true);return state.streamNode;}
  function beginToolGroup(){if(state.streamKind==='tools'&&state.toolGroup)return state.toolGroup;finishLiveStreamSegment();state.streamKind='tools';state.toolGroup=createToolGroup(true);return state.toolGroup;}
  function renderResponseToolCalls(payload){const calls=payload?.message?.toolCalls||payload?.toolCalls||[];if(!Array.isArray(calls)||!calls.length)return;const group=beginToolGroup();for(const call of calls)updateToolRow(group,'toolRequested',call||{});}
  function renderLiveToolEvent(type,payload){const group=beginToolGroup();updateToolRow(group,type,payload||{});}
  function renderConversation(result){$('transcript').textContent='';state.pendingSteeringNodes=[];resetLiveStreamState();const messages=result?.messages||result?.conversation?.messages||[],historicalTools=new Map();for(const m of messages){const role=m.role||m.type||'message';if(role==='assistant'){const reasoning=String(m.reasoning||'');if(reasoning)createReasoningTrace(reasoning,false);const text=messageText(m);if(text)addMessage('assistant',text,'assistant stream-segment');const calls=Array.isArray(m.toolCalls)?m.toolCalls:[];if(calls.length){const group=createToolGroup(false);for(const call of calls){const row=updateToolRow(group,'toolRequested',call||{});historicalTools.set(row.id,group);}finishToolGroup(group);}continue;}if(role==='tool'){const id=m.toolCallId?String(m.toolCallId):null;let group=id?historicalTools.get(id):null;if(!group){group=createToolGroup(false);if(id)historicalTools.set(id,group);}const payload={id:id||undefined,result:messageText(m)};if(m.name)payload.name=m.name;updateToolRow(group,'historicalToolResult',payload);finishToolGroup(group);continue;}addMessage(role,messageText(m),role==='user'?'user':'');}}
  async function refreshAgents(){const agents=await call('agents.list');$('agent').textContent='';for(const a of agents){const o=document.createElement('option');o.value=a.agentId||a.id;o.textContent=a.name||o.value;if(a.default)o.textContent+=' *';$('agent').appendChild(o)}if(!state.agentId||![...$('agent').options].some(o=>o.value===state.agentId))state.agentId=$('agent').value;else $('agent').value=state.agentId;await refreshModels();await refreshSessions();}
  async function refreshModels(){const [models,agent]=await Promise.all([call('models.list'),call('agents.get',{agentId:state.agentId})]);state.agentDescriptor=agent;$('model').textContent='';for(const m of models){const o=document.createElement('option');o.value=m.modelId||m.id||m.name;o.textContent=o.value;$('model').appendChild(o)}const current=agent.modelId||(typeof agent.model==='string'?agent.model:agent.model?.id);if(current&&![...$('model').options].some(o=>o.value===current)){const o=document.createElement('option');o.value=current;o.textContent=current+' (current)';$('model').appendChild(o)}state.modelId=current||$('model').value;if([...$('model').options].some(o=>o.value===state.modelId))$('model').value=state.modelId;const md=models.find(m=>(m.modelId||m.id||m.name)===state.modelId)||null;state.modelDescriptor=md;state.modelSupportsImages=!!md?.capabilities?.images;state.modelSupportsReasoning=!!md?.capabilities?.reasoning;const effort=agent.reasoningEffort??'';if(effort&&![...$('reasoning').options].some(o=>o.value===effort)){const o=document.createElement('option');o.value=effort;o.textContent=effort+' (custom)';$('reasoning').appendChild(o)}$('reasoning').value=effort;$('reasoning').disabled=!state.modelSupportsReasoning;$('reasoning').title=state.modelSupportsReasoning?'Reasoning effort sent with model requests; provider/model support varies':'Selected model does not advertise reasoning support';$('inspectAgent').disabled=!state.agentId;$('inspectModel').disabled=!state.modelId;refreshAttachmentInfo();renderTelemetry();}
  function renderSessions(){const filter=state.sessionFilter.trim().toLowerCase(),box=$('sessions');box.textContent='';for(const s of state.sessionItems){const label=s.name||s.id,haystack=(label+' '+s.id).toLowerCase();if(filter&&!haystack.includes(filter))continue;const row=document.createElement('div');row.className='entity-row';const b=document.createElement('button');b.className='session'+(s.id===state.sessionId?' selected':'');b.textContent=label;b.title=s.id;b.onclick=()=>openSession(s.id);row.append(b,inspectButton('session',paramsAgent({sessionId:s.id}),'Inspect session in Pharo'));box.appendChild(row)}}
  async function refreshSessions(){const page=await call('sessions.list',paramsAgent({limit:100}));const items=page.items||page.sessions||page;state.sessionItems=items;renderSessions();if(!state.sessionId&&items.length)await openSession(items[0].id);}
  async function openSession(id){state.sessionId=id;state.viewEntryId=null;await call('sessions.resume',paramsAgent({sessionId:id}));await Promise.all([refreshTree(),loadSession()]);await refreshSessionsLight();}
  async function refreshSessionsLight(){for(const b of $('sessions').querySelectorAll('.session'))b.classList.toggle('selected',b.title===state.sessionId);}
  async function loadSession(entryId){if(!state.sessionId)return;const p=paramsAgent({sessionId:state.sessionId});if(entryId)p.entryId=entryId;const result=await call('sessions.get',p);state.viewEntryId=entryId||result.viewLeafId||result.currentLeafId;renderConversation(result);$('continueHere').classList.toggle('hidden',!entryId||entryId===result.currentLeafId);}
  async function refreshTree(){if(!state.sessionId)return;const sessionId=state.sessionId,page=await call('sessions.tree',paramsAgent({sessionId,limit:200}));if(state.sessionId!==sessionId)return;const items=page.items||[],$tree=$('tree');$tree.textContent='';for(const e of items){const branchDepth=Math.max(0,Math.min(8,Number(e.branchDepth)||0)),kind=String(e.role||e.type||'entry').toLowerCase(),safeKind=kind.replace(/[^a-z0-9_-]/g,'-');const row=document.createElement('div');row.className='entity-row';row.style.paddingLeft=(branchDepth*.7)+'rem';const b=document.createElement('button');b.className='tree-node'+(e.id===page.currentLeafId?' selected':'');b.title=e.id+(e.childCount>1?' · '+e.childCount+' branches':'');const k=document.createElement('span');k.className='tree-kind tree-kind-'+safeKind;k.textContent=kind;const preview=document.createElement('span');preview.className='tree-preview';preview.textContent=': '+(e.textPreview||e.id);b.append(k,preview);b.onclick=()=>loadSession(e.id);row.append(b,inspectButton('entry',paramsAgent({sessionId,entryId:e.id}),'Inspect conversation entry in Pharo'));$tree.appendChild(row)}}
  function scheduleTreeRefresh(){if(!state.sessionId){state.treeRefreshPending=false;return}state.treeRefreshPending=true;if(state.treeRefreshInFlight)return;state.treeRefreshInFlight=true;queueMicrotask(async()=>{try{while(state.treeRefreshPending){state.treeRefreshPending=false;await refreshTree()}}catch(e){showError(e)}finally{state.treeRefreshInFlight=false;if(state.treeRefreshPending)scheduleTreeRefresh()}})}
  function clearReview(){state.reviewRunId=null;state.reviewNextChangeId=null;state.reviewHasMore=false;state.reviewItemsById.clear();$('reviewSummary').textContent='No reviewed run.';$('changes').textContent='';$('moreChanges').classList.add('hidden');$('changeMeta').textContent='';$('changeDetail').textContent='Select a change.'}
  function renderChangeItem(runId,item){if(!item||!item.id)return null;let view=state.reviewItemsById.get(item.id);if(!view){const row=document.createElement('div');row.className='entity-row';const b=document.createElement('button');b.className='change';const k=document.createElement('div');k.className='kind';const t=document.createElement('div');t.className='target';b.append(k,t);row.append(b,inspectButton('change',{runId,changeId:item.id},'Inspect change record in Pharo'));$('changes').appendChild(row);view={row,b,k,t,item:null};state.reviewItemsById.set(item.id,view)}view.item=item;view.b.className='change'+(item.reverted?' reverted':'');view.k.textContent=(item.scope||'change')+' / '+(item.kind||'')+(item.reverted?' · reverted':'');view.t.textContent=item.target||item.id;view.t.title=item.target||item.id;view.b.title=(item.rollbackSafety||'')+(item.diffAvailable?' · diff available':'');view.b.onclick=()=>showChange(runId,item.id);return view.row}
  function renderLiveReviewSummary(){const items=[...state.reviewItemsById.values()].map(v=>v.item).filter(Boolean),scopes={};let semantic=0,opaque=0,reverted=0;for(const item of items){const scope=item.scope||'change';scopes[scope]=(scopes[scope]||0)+1;if(item.rollbackSafety==='semantic-candidate')semantic++;if(item.rollbackSafety==='opaque')opaque++;if(item.reverted)reverted++}const scopeText=Object.entries(scopes).map(([k,v])=>k+': '+v).join(', ');$('reviewSummary').textContent=items.length+' change(s)'+(scopeText?' · '+scopeText:'')+' · rollback candidates: '+semantic+' · opaque: '+opaque+' · reverted: '+reverted+' · live'}
  function renderLiveChange(runId,item){if(!runId||!item||!item.id)return;if(state.reviewRunId&&state.reviewRunId!==runId)clearReview();state.reviewRunId=runId;renderChangeItem(runId,item);renderLiveReviewSummary()}
  async function refreshReview(runId,afterChangeId=null,append=false){if(!runId){clearReview();return}const params={runId,limit:50};if(afterChangeId)params.afterChangeId=afterChangeId;const review=await call('runs.review',params);if(state.runId&&state.runId!==runId&&state.reviewRunId!==runId)return;state.reviewRunId=runId;if(!append){$('changes').textContent='';state.reviewItemsById.clear()}for(const item of review.items||[])renderChangeItem(runId,item);state.reviewNextChangeId=review.nextChangeId;state.reviewHasMore=!!review.hasMore;$('moreChanges').classList.toggle('hidden',!state.reviewHasMore);const scopes=Object.entries(review.scopeCounts||{}).map(([k,v])=>k+': '+v).join(', ');$('reviewSummary').textContent=review.totalChangeCount+' change(s)'+(scopes?' · '+scopes:'')+' · rollback candidates: '+(review.semanticRollbackCandidateCount||0)+' · opaque: '+(review.opaqueCount||0)+' · reverted: '+(review.revertedCount||0)}
  async function showChange(runId,changeId){try{const d=await call('changes.get',{runId,changeId,maxDiffCharacters:32000});$('changeMeta').textContent=(d.kind||'')+' · '+(d.target||'')+' · rollback: '+(d.rollbackSafety||'unknown')+(d.reverted?' · reverted':'')+(d.diffTruncated?' · diff truncated':'');$('changeDetail').textContent=d.diff||'No textual diff is available for this change.'}catch(e){showError(e)}}
  async function refreshCheckpoints(){const cps=await call('checkpoints.list');$('checkpoints').textContent='';for(const cp of cps){const row=document.createElement('div');row.className='checkpoint';const label=document.createElement('div');label.className='muted';label.textContent=(cp.label||cp.id)+' · journal '+cp.journalIndex;label.title=cp.id;const inspect=inspectButton('checkpoint',{checkpointId:cp.id},'Inspect checkpoint in Pharo');const plan=document.createElement('button');plan.textContent='Plan';plan.onclick=()=>planCheckpoint(cp.id);row.append(label,inspect,plan);$('checkpoints').appendChild(row)}}
  async function planCheckpoint(id){try{const plan=await call('checkpoints.planRollback',{checkpointId:id});state.plannedCheckpointId=plan.rollbackable?id:null;$('rollbackCheckpoint').classList.toggle('hidden',!plan.rollbackable||plan.pendingChangeCount===0);$('changeMeta').textContent='Checkpoint '+id+' · pending '+plan.pendingChangeCount+' · '+(plan.rollbackable?'rollbackable':'BLOCKED');$('changeDetail').textContent=plan.rollbackable?'Rollback preflight passed. This plan covers '+plan.pendingChangeCount+' currently pending journal change(s).':JSON.stringify(plan.blockers||[],null,2)}catch(e){showError(e)}}
  async function createCheckpoint(){const label=prompt('Checkpoint label (optional)')??null;try{const params={};if(label&&label.trim())params.label=label.trim();await call('checkpoints.create',params);await refreshCheckpoints()}catch(e){showError(e)}}
  async function rollbackPlannedCheckpoint(){if(!state.plannedCheckpointId)return;if(!confirm('Rollback all currently pending changes to '+state.plannedCheckpointId+'?'))return;try{const result=await call('checkpoints.rollback',{checkpointId:state.plannedCheckpointId});state.plannedCheckpointId=null;$('rollbackCheckpoint').classList.add('hidden');$('changeMeta').textContent='Rollback completed · '+result.revertedChangeCount+' change(s)';$('changeDetail').textContent=JSON.stringify(result,null,2);if(state.reviewRunId)await refreshReview(state.reviewRunId);await refreshCheckpoints();if(state.sessionId){await refreshTree();await loadSession()}}catch(e){showError(e)}}
  function eventType(e){return e?.data?.type||e?.type||''} function eventPayload(e){return e?.data?.payload}
  function handleEvent(e){if(e.event!=='run.event')return;if(state.runId&&e.runId!==state.runId)return;state.runId=e.runId;state.inspectRunId=e.runId;$('inspectRun').disabled=false;if(Number.isInteger(e.sequence)){if(e.sequence<=state.lastEventSequence)return;state.lastEventSequence=e.sequence}const t=eventType(e),p=eventPayload(e);$('eventInfo').textContent=t+' #'+(e.sequence??'');if(t==='started'){finishLiveStreamSegment();resetRunTelemetry(e.runId);setRunActive(true);scheduleTreeRefresh()}else if(t==='conversationEntryAdded'){scheduleTreeRefresh()}else if(t==='modelRequestStarted'){finishLiveStreamSegment()}else if(t==='contextPrepared'){state.lastContext=p||null;renderTelemetry()}else if(t==='usage'){state.lastUsage=p||null;renderTelemetry();refreshRunTelemetry(e.runId).catch(showError)}else if(t==='textDelta'){appendNode(beginAssistantSegment(),typeof p==='string'?p:'')}else if(t==='reasoningDelta'){updateReasoningTrace(beginReasoningSegment(),typeof p==='string'?p:'',true,true)}else if(t==='modelResponseCompleted'){renderResponseToolCalls(p)}else if(t.startsWith('toolExecution')||['toolInvocationRejected','toolInvocationModified','toolResultIntercepted'].includes(t)){renderLiveToolEvent(t,p)}else if(t==='changeRecorded'){renderLiveChange(e.runId,p)}else if(t==='steeringApplied'){markSteeringApplied(p)}else if(['completed','cancelled','failed','iterationLimitReached'].includes(t)){finishLiveStreamSegment();state.terminalRunId=e.runId;state.inspectRunId=e.runId;setRunActive(false);refreshRunTelemetry(e.runId).catch(showError);refreshReview(e.runId).catch(showError);refreshCheckpoints().catch(showError);refreshTree().catch(showError);refreshSessions().catch(showError)}}
  function setRunActive(active){$('cancel').disabled=!active;$('followUp').disabled=!active;$('runState').textContent=active?'running · composer sends steering':'';$('inspectRun').disabled=!state.inspectRunId;$('prompt').disabled=false;$('send').disabled=false;$('send').textContent=active?'Steer':'Send';$('send').title=active?'Send this text into the currently running agent':'Start a new agent run';$('prompt').placeholder=active?'Steer the running agent… Ctrl+Enter to send.':'Message the coding agent, or type / for commands. Ctrl+Enter to send.';$('attachments').disabled=active;refreshAttachmentInfo();if(!active){state.runId=null;state.subscriptionId=null}}
  function showError(err){addMessage('error',err.message||String(err),'error')}
  const supportedImageTypes=new Set(['image/png','image/jpeg','image/gif','image/webp']);
  const textExtensions=new Set(['txt','md','st','json','jsonl','yaml','yml','xml','html','htm','css','js','mjs','cjs','ts','tsx','jsx','py','c','h','cc','cpp','hpp','cs','java','kt','go','rs','rb','php','sh','bash','zsh','ps1','bat','cmd','sql','toml','ini','cfg','conf','csv','tsv','log','diff','patch','svg']);
  function isTextFile(file){if((file.type||'').startsWith('text/'))return true;if(['application/json','application/xml','application/javascript','application/x-javascript','application/sql','image/svg+xml'].includes(file.type))return true;const i=file.name.lastIndexOf('.');return i>=0&&textExtensions.has(file.name.slice(i+1).toLowerCase())}
  const fileDataURL=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error||new Error('Failed to read '+file.name));r.readAsDataURL(file)});
  function refreshAttachmentInfo(){if($('attachments').disabled){$('attachmentInfo').textContent='Live steering is text-only; attachments are available after this run.';return}const files=[...$('attachments').files];if(!files.length){$('attachmentInfo').textContent='No attachments.';return}const images=files.filter(f=>supportedImageTypes.has(f.type)).length;$('attachmentInfo').textContent=files.length+' attachment(s)'+(images&&!state.modelSupportsImages?' · selected model has no image capability':'')}
  async function readAttachments(){const files=[...$('attachments').files];if(files.length>8)throw new Error('At most 8 attachments are allowed');const result=[];let encodedTotal=0;for(const file of files){if(supportedImageTypes.has(file.type)){if(!state.modelSupportsImages)throw new Error('Selected model does not advertise image support');if(file.size>3*1024*1024)throw new Error(file.name+': image is too large (3 MiB browser limit)');const url=await fileDataURL(file);if(url.length>4*1024*1024)throw new Error(file.name+': encoded image exceeds 4 MiB');encodedTotal+=url.length;result.push({kind:'image',name:file.name,mimeType:file.type||'image/unknown',url})}else if(isTextFile(file)){if(file.size>256*1024)throw new Error(file.name+': text attachment exceeds 256 KiB');const text=await file.text();encodedTotal+=text.length;result.push({kind:'text',name:file.name,mimeType:file.type||'text/plain',text})}else throw new Error(file.name+': only text and image attachments are supported')}if(encodedTotal>6*1024*1024)throw new Error('Combined attachment payload exceeds 6 MiB');return result}
  function hideCommandCompletions(){state.commandCompletionItems=[];state.commandCompletionIndex=0;$('commandCompletions').textContent='';$('commandCompletions').classList.add('hidden')}
  function renderCommandCompletions(items){state.commandCompletionItems=items||[];if(!state.commandCompletionItems.length)return hideCommandCompletions();state.commandCompletionIndex=Math.min(state.commandCompletionIndex,state.commandCompletionItems.length-1);const box=$('commandCompletions');box.textContent='';state.commandCompletionItems.forEach((item,index)=>{const b=document.createElement('button');b.type='button';b.className='command-completion'+(index===state.commandCompletionIndex?' selected':'');const label=document.createElement('span');label.className='label';label.textContent=item.label||item.completion;const desc=document.createElement('span');desc.className='description';desc.textContent=item.description||'';b.append(label,desc);b.onmousedown=e=>e.preventDefault();b.onclick=()=>applyCommandCompletion(index);box.appendChild(b)});box.classList.remove('hidden')}
  async function refreshCommandCompletions(){const text=$('prompt').value;const generation=++state.commandCompletionGeneration;if(!text.startsWith('/')||text.includes('\n')||!state.ws||state.ws.readyState!==1)return hideCommandCompletions();try{const result=await call('commands.complete',paramsAgent({line:text,limit:50}));if(generation!==state.commandCompletionGeneration)return;state.commandCompletionIndex=0;renderCommandCompletions(result?.items||[])}catch(e){if(generation===state.commandCompletionGeneration)hideCommandCompletions()}}
  function moveCommandCompletion(delta){if(!state.commandCompletionItems.length)return;state.commandCompletionIndex=(state.commandCompletionIndex+delta+state.commandCompletionItems.length)%state.commandCompletionItems.length;renderCommandCompletions(state.commandCompletionItems)}
  function applyCommandCompletion(index=state.commandCompletionIndex){const item=state.commandCompletionItems[index];if(!item)return false;const prompt=$('prompt');prompt.value=item.completion||'';prompt.focus();prompt.setSelectionRange(prompt.value.length,prompt.value.length);hideCommandCompletions();if(item.kind==='command'&&prompt.value.endsWith(' '))refreshCommandCompletions();return true}
  function slashCommandName(line){return line.slice(1).trim().split(/\s+/,1)[0].toLowerCase()}
  function formatCommandResult(name,result){if(name==='help'&&Array.isArray(result))return result.map(c=>(c.usage||('/'+c.name))+' — '+(c.description||'')).join('\n');if(name==='sessions'){const items=result?.items||result?.sessions||result||[];return items.length?items.map(s=>(s.name||s.id)+'  ['+s.id+']').join('\n'):'No durable sessions.'}if(name==='models'&&Array.isArray(result))return result.length?result.map(m=>(m.name||m.modelId||m.id)+'  ['+(m.providerId||'provider?')+']').join('\n'):'No configured models.';if(name==='skills'&&Array.isArray(result))return result.length?result.map(s=>(s.active?'* ':'  ')+(s.name||'skill')+(s.description?' — '+s.description:'')).join('\n'):'No skills available.';if(name==='model')return 'Model for '+(result?.name||result?.id||state.agentId)+': '+(result?.model||result?.modelId||state.modelId||'');if(name==='reasoning')return 'Reasoning for '+(result?.name||result?.id||state.agentId)+': '+(result?.reasoningEffort??'provider default');if(name==='new'||name==='continue')return 'Selected session '+(result?.name||result?.id||'')+(result?.id?'  ['+result.id+']':'');if(name==='checkpoint')return 'Created checkpoint '+(result?.label||result?.id||'')+(result?.id?'  ['+result.id+']':'');if(name==='checkpoints'){const items=result?.items||result||[];return items.length?items.map(c=>(c.label||c.id)+'  ['+c.id+']').join('\n'):'No checkpoints.'}return typeof result==='string'?result:JSON.stringify(result,null,2)}
  async function executeSlashCommand(text,attachments){if(attachments.length)throw new Error('Slash commands do not accept attachments');const name=slashCommandName(text);const result=await call('commands.executeLine',paramsAgent({line:text}));$('prompt').value='';hideCommandCompletions();if(name==='new'||name==='continue'){if(result?.id)state.sessionId=result.id;await refreshSessions();if(state.sessionId){await refreshTree();await loadSession()}}else if(name==='checkpoint'||name==='checkpoints'){await refreshCheckpoints()}else if(name==='model'||name==='reasoning'){if(/\s+\S/.test(text)){await call('runtime.profile.save',{})}await refreshModels()}addMessage('command',text,'user');addMessage('command result',formatCommandResult(name,result),'tool');return result}
  async function sendSteering(text){const runId=state.runId;if(!runId)return false;finishLiveStreamSegment();const node=addMessage('user',text,'user steering-pending');state.pendingSteeringNodes.push({text,node});$('prompt').value='';hideCommandCompletions();try{await call('runs.steer',{runId,message:text});$('eventInfo').textContent='steering queued';$('prompt').focus();return true}catch(e){const index=state.pendingSteeringNodes.findIndex(each=>each.node===node);if(index>=0)state.pendingSteeringNodes.splice(index,1);node.remove();$('prompt').value=text;$('prompt').focus();throw e}}
  function markSteeringApplied(payload){const text=String(payload??''),index=state.pendingSteeringNodes.findIndex(each=>each.text===text);if(index<0)return;const pending=state.pendingSteeringNodes.splice(index,1)[0];pending.node.classList.remove('steering-pending');pending.node.classList.add('steering-applied')}
  async function sendPrompt(){const text=$('prompt').value.trim();if(!text)return;try{if(text.startsWith('/')){const attachments=await readAttachments();await executeSlashCommand(text,attachments);return}if(state.runId){if($('attachments').files.length)throw new Error('Attachments cannot be added to live steering; send them after the current run completes.');await sendSteering(text);return}const attachments=await readAttachments();if(!state.sessionId){const s=await call('sessions.new',paramsAgent({name:null}));state.sessionId=s.id}const suffix=attachments.length?'\n'+attachments.map(a=>'[attached: '+a.name+']').join('\n'):'';addMessage('user',text+suffix,'user');state.terminalRunId=null;state.lastEventSequence=0;state.subscriptionId=null;resetRunTelemetry(null);clearReview();const run=await call('runs.start',paramsAgent({sessionId:state.sessionId,prompt:text,attachments}));$('prompt').value='';$('attachments').value='';refreshAttachmentInfo();const id=run.runId||run.id;state.inspectRunId=id;state.lastTelemetry=run.telemetry||state.lastTelemetry;$('inspectRun').disabled=!id;renderTelemetry();if(state.terminalRunId===id){await refreshRunTelemetry(id);await loadSession();return}state.runId=id;if(run.status==='running'){setRunActive(true);await refreshReview(id);await resumeRunSubscription()}else{state.terminalRunId=id;setRunActive(false);await refreshRunTelemetry(id);await loadSession()}}catch(e){showError(e)}}
  async function control(method){if(!state.runId)return;const text=(method==='runs.cancel')?null:prompt('Follow-up message');if(method!=='runs.cancel'&&!text)return;try{await call(method,text?{runId:state.runId,message:text}:{runId:state.runId})}catch(e){showError(e)}}
  async function resumeRunSubscription(){if(!state.runId)return;try{const sub=await call('runs.subscribe',{runId:state.runId,afterSequence:state.lastEventSequence});state.subscriptionId=sub.subscriptionId||null}catch(e){const code=e.response?.error?.code;if(code==='event_replay_expired'){await loadSession();const earliest=e.response?.error?.details?.earliestRetainedSequence||1;state.lastEventSequence=Math.max(0,earliest-1);const sub=await call('runs.subscribe',{runId:state.runId,afterSequence:state.lastEventSequence});state.subscriptionId=sub.subscriptionId||null}else if(code==='run_not_found'){setRunActive(false)}else throw e}}
  async function restoreActiveRun(){const snap=await call('state.snapshot');const active=(snap.runs||[]).find(r=>r.agentId===state.agentId&&r.status==='running');if(!active)return;state.sessionId=active.sessionId;await openSession(state.sessionId);state.runId=active.id;state.inspectRunId=active.id;state.lastTelemetry=active.telemetry||null;state.lastEventSequence=0;$('inspectRun').disabled=false;renderTelemetry();setRunActive(true);await refreshRunTelemetry(active.id);await refreshReview(active.id);await resumeRunSubscription()}
  function connect(){const proto=location.protocol==='https:'?'wss:':'ws:';state.ws=new WebSocket(proto+'//'+location.host+'/ws');state.ws.onopen=async()=>{status('connected',true);try{await call('protocol.hello');await refreshAgents();await refreshCheckpoints();if(state.runId)await resumeRunSubscription();else await restoreActiveRun()}catch(e){showError(e)}};state.ws.onclose=()=>{status('disconnected');state.subscriptionId=null;for(const p of state.pending.values())p.reject(new Error('WebSocket disconnected'));state.pending.clear();setTimeout(connect,1500)};state.ws.onerror=()=>status('connection error');state.ws.onmessage=ev=>{let msg;try{msg=JSON.parse(ev.data)}catch(e){return showError(e)}if(msg.type==='event')return handleEvent(msg);if(msg.type==='response'&&state.pending.has(msg.id)){const p=state.pending.get(msg.id);state.pending.delete(msg.id);p.resolve(msg)}}}
  $('agent').onchange=async()=>{state.agentId=$('agent').value;state.sessionId=null;resetRunTelemetry(null);try{await refreshModels();await refreshSessions()}catch(e){showError(e)}};
  $('model').onchange=async()=>{try{await call('agents.setModel',{agentId:state.agentId,modelId:$('model').value});state.modelId=$('model').value;await call('runtime.profile.save',{});await refreshModels()}catch(e){showError(e)}};
  $('reasoning').onchange=async()=>{try{const value=$('reasoning').value;await call('agents.setReasoningEffort',{agentId:state.agentId,reasoningEffort:value===''?null:value});await call('runtime.profile.save',{});await refreshModels()}catch(e){showError(e)}};
  $('theme').onchange=()=>applyThemePreference($('theme').value,true);
  $('inspectAgent').onclick=()=>inspectEntity('agent',{agentId:state.agentId}).catch(showError);
  $('inspectModel').onclick=()=>inspectEntity('model',{modelId:state.modelId}).catch(showError);
  $('inspectRun').onclick=()=>{if(state.inspectRunId)inspectEntity('run',{runId:state.inspectRunId}).catch(showError)};
  $('newSession').onclick=async()=>{try{const s=await call('sessions.new',paramsAgent({}));state.sessionId=s.id;await refreshSessions();await refreshTree();await loadSession()}catch(e){showError(e)}};
  $('continueHere').onclick=async()=>{if(!state.viewEntryId)return;try{await call('sessions.selectEntry',paramsAgent({sessionId:state.sessionId,entryId:state.viewEntryId}));await refreshTree();await loadSession()}catch(e){showError(e)}};
  $('createCheckpoint').onclick=createCheckpoint;$('rollbackCheckpoint').onclick=rollbackPlannedCheckpoint;
  $('moreChanges').onclick=()=>{if(state.reviewRunId&&state.reviewHasMore)refreshReview(state.reviewRunId,state.reviewNextChangeId,true).catch(showError)};
  $('sessionFilter').addEventListener('input',()=>{state.sessionFilter=$('sessionFilter').value;renderSessions()});$('attachments').onchange=refreshAttachmentInfo;$('send').onclick=sendPrompt;$('prompt').addEventListener('input',()=>refreshCommandCompletions());$('prompt').addEventListener('keydown',e=>{const open=!$('commandCompletions').classList.contains('hidden')&&state.commandCompletionItems.length;if(open&&e.key==='ArrowDown'){e.preventDefault();moveCommandCompletion(1);return}if(open&&e.key==='ArrowUp'){e.preventDefault();moveCommandCompletion(-1);return}if(open&&(e.key==='Tab'||(e.key==='Enter'&&!e.ctrlKey&&!e.metaKey))){e.preventDefault();applyCommandCompletion();return}if(open&&e.key==='Escape'){e.preventDefault();hideCommandCompletions();return}if(e.key==='Enter'&&e.ctrlKey){e.preventDefault();sendPrompt()}});$('cancel').onclick=()=>control('runs.cancel');$('followUp').onclick=()=>control('runs.followUp');$('refresh').onclick=()=>refreshAgents().catch(showError);applyThemePreference(readThemePreference());const onSystemThemeChange=()=>{if(state.themePreference==='auto')applyThemePreference('auto')};if(themeMedia.addEventListener)themeMedia.addEventListener('change',onSystemThemeChange);else if(themeMedia.addListener)themeMedia.addListener(onSystemThemeChange);connect();
})();
});
